name: CI  

on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
    build:
      name: flutter build
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      env:
        JAVA_VERSION: "11.0"
        FLUTTER_VERSION: "2.8.1"
      steps:
        - uses: actions/checkout@v2
        - uses: actions/setup-java@v1
          with:
            java-version: $JAVA_VERSION
        - uses: subosito/flutter-action@v1
          with:
            flutter-version: $FLUTTER_VERSION
        - run: flutter pub get
        - run: flutter analyze
        - run: flutter test