name: CI  

on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  build-android:
    name: Build for Android
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'
    - run: flutter pub get
    # - run: flutter test
    - run: cd example; flutter build apk
    - run: cd example; flutter build appbundle
  build-ios:
    name: Build for iOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.3.3'
    - run: flutter pub get
    # - run: flutter test
    - run: cd example; flutter build ios --release --no-codesign
