name: CI  

on: [push, pull_request]

jobs:
  # This workflow contains a single job called "build"
  build-android:
    name: flutter build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '11'
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build apk
    - run: flutter build appbundle
  build-ios:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '2.8.1'
    - run: flutter pub get
    - run: flutter test
    - run: flutter build ios --release --no-codesign