name: CI  

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.2.3'
        channel: stable

    - name: Doctor
      run: flutter doctor -v

    - name: Analyze
      run: flutter analyze .

#    - name: Run Tests
#      run: flutter test

    - name: Get dependencies
      run: flutter pub get

    - name: Change to example directory
      run: cd example

    - name: Build for Android (apk)
      run: flutter build apk
    
    - name: Build for Android (appbundle)
      run: flutter build appbundle

    - name: Build for iOS
      run: flutter build ios --release --no-codesign
